/**
 * Reusability: is this repository a LIBRARY or an APPLICATION?
 *
 * The single most consequential distinction for a tool whose purpose is finding reusable
 * implementations — and one that popularity, tests, maintenance and even completeness are
 * all blind to.
 *
 * An Android app that uses Room contains schema definitions, DAOs, migrations and
 * transactional writes. It therefore scores *well* on a persistence checklist, and can
 * outrank an actual persistence library. Observed live: a plant-care app ranked first for
 * "local persistence". Nothing was wrong with the measurement; the question being measured
 * was incomplete.
 *
 * An application is not useless — it is a working example, and sometimes the only one —
 * but it is `REFERENCE_ONLY` in practice, because you cannot depend on it. So this is
 * scored, explained, and fed to reuse-mode assessment rather than used as a filter.
 *
 * All signals come from data deep analysis already fetches: the tree, the manifests, the
 * topics and the description. No extra API calls.
 */

import type { Dependency, RepoMetadata } from "../types/index.js";

export type RepositoryKind = "library" | "application" | "example" | "mixed" | "unknown";

export interface ReusabilityAssessment {
  kind: RepositoryKind;
  /** 0–1, higher = more reusable as a dependency. Feeds the ranking axis. */
  score: number;
  /** 0–1 confidence in the classification itself. */
  confidence: number;
  /** Human-readable evidence, both directions. */
  signals: string[];
}

export interface ReusabilityInput {
  metadata: RepoMetadata;
  filePaths?: string[];
  dependencies?: Dependency[];
  /** Raw manifest text, when available — publishing config is the strongest signal. */
  manifestContents?: string[];
  readme?: string;
}

/** Paths that indicate a distributable library. */
const LIBRARY_PATHS: [RegExp, string][] = [
  [/(^|\/)(gradle\/libs\.versions\.toml)$/i, "version catalog"],
  [/(^|\/)(api|public)\/.*\.api$/i, "binary-compatibility API dump"],
  [/(^|\/)\.api\//i, "API surface tracking"],
];

/** Paths that indicate a runnable application. */
const APP_PATHS: [RegExp, string][] = [
  [/(^|\/)Dockerfile$/i, "Dockerfile"],
  [/(^|\/)docker-compose\.ya?ml$/i, "docker-compose"],
  [/(^|\/)(fastlane|Fastfile)/i, "release automation (fastlane)"],
  [/(^|\/)(screenshots?|fastlane\/metadata)\//i, "screenshots"],
  [/(^|\/)\.github\/workflows\/.*(deploy|release-app|publish-app)/i, "deployment workflow"],
  [/(^|\/)(k8s|kubernetes|helm|terraform)\//i, "infrastructure manifests"],
  [/(^|\/)(procfile|vercel\.json|netlify\.toml|app\.yaml)$/i, "hosting configuration"],
];

/** Publishing configuration — the strongest library signal there is. */
const PUBLISH_MARKERS: [RegExp, string][] = [
  [/\bmaven-publish\b|\bcom\.vanniktech\.maven\.publish\b|\bsigning\b.*\bpublish/i, "maven-publish plugin"],
  [/\bpublishing\s*\{/i, "gradle publishing block"],
  [/\bapply\s+plugin:\s*['"]com\.jfrog\.bintray['"]/i, "artifact publishing"],
  [/"private"\s*:\s*false/i, "npm publishable"],
  [/\b(setuptools|poetry|hatchling|flit)\b/i, "python packaging"],
  [/\[project\]|\[tool\.poetry\]/i, "python project metadata"],
  [/\bcrate-type\b|\[lib\]/i, "cargo library target"],
  [/\bs\.summary\b|\bspec\.summary\b/i, "podspec"],
  [/\bproducts:\s*\[[\s\S]{0,200}\.library\(/i, "SwiftPM library product"],
];

/** Application configuration in build files. */
const APP_MARKERS: [RegExp, string][] = [
  [/\bapplicationId\s*[=\s]/i, "Android applicationId"],
  [/\bcom\.android\.application\b/i, "Android application plugin"],
  [/\[\[bin\]\]|\bsrc\/main\.rs\b/i, "cargo binary target"],
  [/\bexecutable\(/i, "SwiftPM executable product"],
  [/"bin"\s*:/i, "npm bin entry"],
];

/**
 * Bare "client" is deliberately absent.
 *
 * "Android client for a self-hosted Flux server" describes an APP, not a library — and it
 * was scoring a library point, which tied against the app signals and produced "mixed",
 * skipping the REFERENCE_ONLY gate entirely. A one-star RSS reader then won "biometric app
 * lock". "client library" and "client SDK" are still library signals; "client for X" is not.
 */
const LIBRARY_TOPICS = /\b(library|libraries|sdk|framework|toolkit|wrapper|binding|plugin|package)\b|\bclient (library|sdk)\b/i;
const APP_TOPICS = /\b(app|application|android-app|ios-app|demo|sample|example|tutorial|starter|boilerplate|template|clone|portfolio)\b/i;

/**
 * Whether a Gradle module is an application/demo module rather than the library.
 *
 * The `*App` suffix matters as much as the explicit names: `composeApp` is what the
 * JetBrains Kotlin Multiplatform wizard calls the APPLICATION module, so every KMP sample
 * generated by it was being counted as a library module — `ChirpAppDesktopKMP`, a chat
 * demo, was classified `library` with a perfect 1.00 reusability score while simultaneously
 * being flagged "described as an app/demo/template". `androidApp`, `iosApp`, `desktopApp`
 * and `serverApp` fall out of the same rule.
 */
function isDemoModule(name: string): boolean {
  return /^(app|sample|samples|sampleapp|demo|demos|example|examples|playground)$/i.test(name)
    // Deployable targets of a full-stack project, not libraries. `chat-multiplatform` has
    // `server` and `web` beside its Compose app; counting those as library modules made a
    // full-stack chat demo the top result for "WebSocket transport with reconnection".
    || /^(server|web|website|site|backend|frontend|desktop|cli|bot|daemon|service)$/i.test(name)
    || /app$/i.test(name);
}

/** Split identifiers so word-boundary patterns behave: WorkManagerExample -> work manager example. */
function humanise(text: string): string {
  return text
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[_\-.]+/g, " ")
    .replace(/\s+/g, " ")
    .toLowerCase();
}

export function assessReusability(input: ReusabilityInput): ReusabilityAssessment {
  const signals: string[] = [];
  let library = 0;
  let application = 0;
  let evidenceCount = 0;

  const files = input.filePaths ?? [];
  const manifests = (input.manifestContents ?? []).join("\n");
  // Repository names are identifiers, so `\bexample\b` never matches inside
  // "WorkManagerExample" — the same word-boundary trap as
  // symbol-role matching. Split camelCase, kebab and snake before testing.
  const meta = humanise(
    `${input.metadata.ref.name} ${input.metadata.description ?? ""} ${input.metadata.topics.join(" ")}`,
  );

  /*
   * Gradle module layout — the sharpest structural signal there is for a JVM project, and
   * the one that tells the marker loops below how to read themselves.
   *
   *   [app]                     the app IS the repository         -> application
   *   [app, lib]                app is a demo, lib is the library -> library
   *   [core-paginglist, sample] sample is a demo                  -> library
   *
   * An earlier heuristic counted AndroidManifests and treated any `app/` directory as a
   * shipped sample. But `app/` is the conventional module name for the APPLICATION in
   * Android, not for a sample — so a wallpaper app scored a library point, tied against its
   * own application signals, landed on "mixed", skipped the REFERENCE_ONLY gate, and
   * outranked an actual paging library.
   *
   * What separates the two is whether anything else is there: a library repository has a
   * module that is not an app.
   */
  const modules = [...new Set(
    files
      .filter((f) => /^[^/]+\/build\.gradle(\.kts)?$/.test(f))
      .map((f) => f.split("/")[0] as string),
  )];
  const libraryModules = modules.filter((m) => !isDemoModule(m));
  /** A library that ships a runnable demo — the good shape, not an application. */
  const shipsDemoAlongsideLibrary = libraryModules.length > 0 && modules.length > libraryModules.length;

  // --- publishing configuration: the strongest signal in either direction -----
  for (const [re, label] of PUBLISH_MARKERS) {
    if (manifests && re.test(manifests)) {
      library += 3; evidenceCount++;
      signals.push(`+ ${label}`);
      break;
    }
  }
  /*
   * A library's demo module has an `applicationId` and the `com.android.application`
   * plugin, because it is an Android app — that is what a demo IS. Counting those as
   * evidence of an application punishes exactly the repositories that document themselves
   * best: `ReconnectWebSocketWrapper` ships `lib` plus a demo `app`, was marked down for
   * the demo's applicationId, landed on "mixed" instead of "library", and finished below
   * a MUD game and a chat sample that merely mention websockets.
   *
   * The markers still count when there is no library module to explain them.
   */
  if (!shipsDemoAlongsideLibrary) {
    for (const [re, label] of APP_MARKERS) {
      if (manifests && re.test(manifests)) {
        application += 3; evidenceCount++;
        signals.push(`- ${label}`);
        break;
      }
    }
  }

  // --- structural paths ------------------------------------------------------
  for (const [re, label] of LIBRARY_PATHS) {
    if (files.some((f) => re.test(f))) { library += 1; evidenceCount++; signals.push(`+ ${label}`); }
  }
  for (const [re, label] of APP_PATHS) {
    if (files.some((f) => re.test(f))) { application += 1.5; evidenceCount++; signals.push(`- ${label}`); }
  }

  if (modules.length > 0) {
    if (libraryModules.length > 0) {
      library += 2; evidenceCount++;
      signals.push(
        shipsDemoAlongsideLibrary
          ? `+ library module${libraryModules.length > 1 ? "s" : ""} (${libraryModules.slice(0, 2).join(", ")}) alongside a demo`
          : `+ library module${libraryModules.length > 1 ? "s" : ""}: ${libraryModules.slice(0, 2).join(", ")}`,
      );
    } else {
      application += 2.5; evidenceCount++;
      signals.push(`- the only module is the application itself (${modules.join(", ")})`);
    }
  }

  // --- naming and topics -----------------------------------------------------
  if (LIBRARY_TOPICS.test(meta)) { library += 1.5; evidenceCount++; signals.push("+ described as a library/SDK"); }
  if (APP_TOPICS.test(meta)) { application += 1.5; evidenceCount++; signals.push("- described as an app/demo/template"); }

  // README install instructions naming a dependency coordinate are near-conclusive.
  if (input.readme && /(\bimplementation\s*\(?["']|\bnpm i(nstall)?\s+[\w@/-]|\bpip install\s+[\w-]|\badd\s+.+\s+to\s+your\s+(dependencies|Gemfile|Cargo\.toml))/i.test(input.readme)) {
    library += 2; evidenceCount++;
    signals.push("+ README documents installing it as a dependency");
  }

  // --- verdict ---------------------------------------------------------------
  const total = library + application;
  const kind: RepositoryKind =
    evidenceCount === 0 ? "unknown"
      : total === 0 ? "unknown"
      : library >= application * 2 ? "library"
      : application >= library * 2 ? (/\b(demo|sample|example|tutorial|starter|boilerplate|playground)\b/i.test(meta) ? "example" : "application")
      : "mixed";

  // Score: 1.0 a clear library, 0.15 a clear application. An application is not worthless —
  // it is a working example — but you cannot depend on it, so it must not win a search for
  // a reusable implementation.
  const score =
    kind === "library" ? 1
      : kind === "mixed" ? 0.6
      : kind === "example" ? 0.2
      : kind === "application" ? 0.15
      : 0.5;   // unknown: neutral, not penalised

  return {
    kind,
    score,
    confidence: evidenceCount === 0 ? 0.1 : Math.min(0.9, 0.35 + evidenceCount * 0.15),
    signals: signals.slice(0, 5),
  };
}
